env_config:
  env_name: 'Ant-v2'
  max_episode_step: 1000
  env_seed: 10

model_config:
  policy_hidden_layers:
    - 128
    - 128
  value_hidden_layers:
    - 128
    - 128
  action_std: 0.2

seed: 10
lr: 0.0005
gamma: 0.999
rho: 0.001
num_agents: 4
buffer_size: 1000000
batch_size: 256
device: 'cpu'
results_path: '/home/xukang/GitRepo/DPP_exploration/results/'
max_timestep: 800000
start_training_step: 2000
train_policy_delay: 2
save_interval: 100

noise_std: 0.2
noise_clip: 0.5

diversity_importance: 0.2