env_config:
  env_name: 'Swimmer-v2'
  max_episode_length: 5000

model_config:
  policy_hidden_layers:
    - 128
    - 128
  value_hidden_layers:
    - 128
    - 128
  action_std: 0.1

lr: 0.0005
gamma: 0.999
rho: 0.001
num_agents: 4
buffer_size: 1000000
batch_size: 256
device: 'cuda'
results_path: '/home/xukang/GitRepo/DPP_exploration/results/'
max_timestep: 1500000
start_training_step: 2000
train_policy_delay: 2
save_interval: 250

noise_std: 0.2
noise_clip: 0.5